// Tipos para o sistema de atividades avançado

export interface ActivityType {
  id: string;
  name: string;
  description: string;
  icon: string;
  configSchema: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ActivityConfig {
  id: string;
  activityId: string;
  typeId: string;
  configData: any;
  createdAt: string;
  updatedAt: string;
}

export interface Team {
  id: string;
  activityId: string;
  name: string;
  description?: string;
  maxMembers: number;
  createdBy: string;
  status: 'active' | 'inactive' | 'completed';
  createdAt: string;
  updatedAt: string;
  memberCount?: number;
  creatorName?: string;
}

export interface TeamMember {
  id: string;
  teamId: string;
  userId: string;
  role: 'leader' | 'member' | 'observer';
  joinedAt: string;
  leftAt?: string;
  status: 'active' | 'inactive' | 'removed';
  userName?: string;
}

export interface RubricCriterion {
  id: string;
  name: string;
  description: string;
  weight: number;
  levels: RubricLevel[];
}

export interface RubricLevel {
  score: number;
  label: string;
  description: string;
}

export interface RubricCriteria {
  criteria: RubricCriterion[];
}

export interface Rubric {
  id: string;
  name: string;
  description?: string;
  criteria: RubricCriteria;
  maxScore: number;
  weightedScoring: boolean;
  autoGradingEnabled: boolean;
  createdBy: string;
  isTemplate: boolean;
  createdAt: string;
  updatedAt: string;
  creatorName?: string;
}

export interface ActivityRubric {
  id: string;
  activityId: string;
  rubricId: string;
  weight: number;
  isPrimary: boolean;
  createdAt: string;
}

export interface DetailedEvaluation {
  id: string;
  submissionId: string;
  rubricId: string;
  criterionScores: Record<string, number>;
  totalScore: number;
  autoGenerated: boolean;
  evaluatorId?: string;
  feedback?: string;
  createdAt: string;
  updatedAt: string;
  evaluatorName?: string;
}

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon?: string;
  category: string;
  points: number;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
  criteria: any;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface UserAchievement {
  id: string;
  userId: string;
  achievementId: string;
  earnedAt: string;
  activityId?: string;
  pointsEarned: number;
  achievement?: Achievement;
}

export interface UserPoints {
  id: string;
  userId: string;
  points: number;
  source: string;
  sourceId?: string;
  description?: string;
  earnedAt: string;
}

export interface ActivityAnalytics {
  id: string;
  activityId: string;
  userId: string;
  eventType: string;
  eventData?: any;
  sessionId?: string;
  timestamp: string;
  userName?: string;
}

export interface PeerReview {
  id: string;
  submissionId: string;
  reviewerId: string;
  reviewedSubmissionId: string;
  rating?: number;
  feedback?: string;
  criteriaScores?: Record<string, number>;
  isAnonymous: boolean;
  status: 'pending' | 'completed' | 'skipped';
  submittedAt?: string;
  createdAt: string;
  updatedAt: string;
  reviewerName?: string;
}

export interface QuizQuestion {
  id: string;
  activityId: string;
  questionText: string;
  questionType: 'multiple_choice' | 'true_false' | 'short_answer' | 'essay' | 'drag_drop' | 'matching';
  options?: any;
  correctAnswer?: any;
  points: number;
  explanation?: string;
  mediaUrl?: string;
  orderIndex: number;
  createdAt: string;
  updatedAt: string;
}

export interface QuizResponse {
  id: string;
  submissionId: string;
  questionId: string;
  userAnswer?: any;
  isCorrect?: boolean;
  pointsEarned: number;
  timeSpent?: number;
  attemptNumber: number;
  answeredAt: string;
}

export interface CollaborationSession {
  id: string;
  activityId: string;
  teamId?: string;
  sessionName: string;
  sessionData?: any;
  isActive: boolean;
  createdBy: string;
  createdAt: string;
  endedAt?: string;
}

export interface CollaborationParticipant {
  id: string;
  sessionId: string;
  userId: string;
  joinedAt: string;
  leftAt?: string;
  isActive: boolean;
  userName?: string;
}

// Tipos para configurações específicas de cada tipo de atividade

export interface QuizConfig {
  timeLimit?: number; // em minutos
  allowMultipleAttempts: boolean;
  maxAttempts?: number;
  shuffleQuestions: boolean;
  shuffleOptions: boolean;
  showCorrectAnswers: boolean;
  showExplanations: boolean;
  passingScore?: number;
  questions: QuizQuestion[];
}

export interface CollaborativeProjectConfig {
  phases: ProjectPhase[];
  allowTeamFormation: boolean;
  maxTeamSize: number;
  minTeamSize: number;
  requiresPeerReview: boolean;
  deliverables: Deliverable[];
}

export interface ProjectPhase {
  id: string;
  name: string;
  description: string;
  startDate?: string;
  endDate?: string;
  deliverables: string[];
  weight: number;
}

export interface Deliverable {
  id: string;
  name: string;
  description: string;
  type: 'document' | 'presentation' | 'code' | 'media' | 'other';
  required: boolean;
  maxFileSize?: number;
  allowedFormats?: string[];
}

export interface VirtualLabConfig {
  simulation: LabSimulation;
  objectives: string[];
  equipment: LabEquipment[];
  procedures: LabProcedure[];
  safetyNotes?: string[];
}

export interface LabSimulation {
  type: 'chemistry' | 'physics' | 'biology' | 'computer_science' | 'other';
  environment: string;
  parameters: Record<string, any>;
}

export interface LabEquipment {
  id: string;
  name: string;
  description: string;
  quantity: number;
  properties: Record<string, any>;
}

export interface LabProcedure {
  step: number;
  instruction: string;
  expectedResult?: string;
  tips?: string[];
  warnings?: string[];
}

export interface PresentationConfig {
  allowAudience: boolean;
  enablePolls: boolean;
  enableQA: boolean;
  enableChat: boolean;
  recordSession: boolean;
  maxDuration?: number;
  slides?: PresentationSlide[];
}

export interface PresentationSlide {
  id: string;
  title: string;
  content: string;
  type: 'text' | 'image' | 'video' | 'interactive' | 'poll';
  order: number;
  interactiveElements?: InteractiveElement[];
}

export interface InteractiveElement {
  id: string;
  type: 'poll' | 'quiz' | 'annotation' | 'drawing';
  config: any;
  position: { x: number; y: number };
}

export interface PortfolioConfig {
  sections: PortfolioSection[];
  allowReflections: boolean;
  requiresApproval: boolean;
  publicView: boolean;
  categories: string[];
}

export interface PortfolioSection {
  id: string;
  name: string;
  description: string;
  required: boolean;
  maxItems?: number;
  allowedTypes: string[];
}

export interface CodingChallengeConfig {
  language: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  timeLimit?: number;
  testCases: TestCase[];
  starterCode?: string;
  allowedLibraries?: string[];
  executionEnvironment: string;
}

export interface TestCase {
  id: string;
  input: any;
  expectedOutput: any;
  description?: string;
  isHidden: boolean;
  weight: number;
}

export interface DiscussionConfig {
  topics: DiscussionTopic[];
  allowAnonymous: boolean;
  requireModeration: boolean;
  enableVoting: boolean;
  enableThreads: boolean;
  maxPostLength?: number;
}

export interface DiscussionTopic {
  id: string;
  title: string;
  description: string;
  required: boolean;
  minPosts?: number;
  category?: string;
}

// Tipos para analytics e relatórios

export interface ActivityReport {
  activityId: string;
  activityName: string;
  totalSubmissions: number;
  averageScore: number;
  completionRate: number;
  timeSpent: {
    average: number;
    median: number;
    min: number;
    max: number;
  };
  participationByDay: Record<string, number>;
  scoreDistribution: Record<string, number>;
  commonErrors?: string[];
  topPerformers: UserPerformance[];
}

export interface UserPerformance {
  userId: string;
  userName: string;
  score: number;
  completionTime: number;
  attempts: number;
  rank: number;
}

export interface GamificationStats {
  totalPoints: number;
  level: number;
  achievements: UserAchievement[];
  streak: number;
  rank: number;
  recentActivity: ActivitySummary[];
}

export interface ActivitySummary {
  activityId: string;
  activityName: string;
  score: number;
  completedAt: string;
  pointsEarned: number;
}

// Tipos para notificações e eventos

export interface ActivityNotification {
  id: string;
  userId: string;
  type: 'achievement' | 'deadline' | 'team_invite' | 'peer_review' | 'grade_released';
  title: string;
  message: string;
  data?: any;
  read: boolean;
  createdAt: string;
}

export interface ActivityEvent {
  id: string;
  type: 'activity_created' | 'submission_received' | 'team_formed' | 'achievement_earned';
  activityId?: string;
  userId?: string;
  data: any;
  timestamp: string;
}